## 常用包的总结

#### 1.Numpy
#### 2.Pandas
#### 3.Scipy

In [2]:
import numpy as np
import pandas as pd

In [4]:
path = '/home/LF/datasets/santanderCustomerTransactionPrediction/'
data = pd.read_csv(path+'train.csv')

In [5]:
data.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155   ...      2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250   ...      4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514   ...     -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

## np.unique

找出某个属性中有唯一值的行

In [19]:
_,index_,count_ = np.unique(data['var_0'],return_counts=True,return_index=True)
# 记录该列中的每一个值的状态
col_state = np.zeros(len(data['var_0']))
col_state[index_[count_==1]]=1
# 选出那些唯一值的行idx
np.argwhere(col_state>0)[:,0]

In [20]:
count_
index_

array([1, 1, 1, ..., 1, 1, 2])

array([165885, 131672,  10693, ..., 180332, 151150,  72728])

## map函数进行频繁编码

In [28]:
data['cnt_var_0'] = data['var_0'].map(data['var_0'].value_counts())

In [31]:
data[['var_0','cnt_var_0']]

var_0  cnt_var_0
0        8.9255          6
1       11.5006          2
2        8.6093          4
3       11.0604          3
4        9.8369          3
5       11.4763          2
6       11.8091          3
7       13.5580          2
8       16.1071          1
9       12.5088          2
10       5.0702          3
11      12.7188          4
12       8.7671          3
13      16.3699          1
14      13.8080          2
15       3.9416          2
16       5.0615          1
17       8.4199          4
18       4.8750          2
19       4.4090          2
20      12.6700          4
21       8.3918          4
22      10.2031          3
23      15.0029          1
24       5.9240          2
25       8.2703          5
26      15.6567          1
27      10.7166          3
28       7.8010          4
29       5.3301          2
...         ...        ...
199970  15.5794          1
199971  14.5745          1
199972   7.4206          1
199973   8.7758          3
199974  16.2010          1
199975   7.5238          6
199976   7.9663          5
199977   7.3884          3
199978  12.2015          7
199979  10.8208          3
199980   7.9618          3
199981  12.8140          3
199982  11.8224          3
199983  15.3063          2
199984  11.3184          2
199985   9.0249          3
199986  12.0298          3
199987   8.0438          2
199988  10.8657          4
199989  11.7554          5
199990  14.1475          2
199991   9.9909          2
199992  12.2825          3
199993  13.2152          1
199994  12.3925          5
199995  11.4880          4
199996   4.9149          3
199997  11.2232          5
199998   9.7148          3
199999  10.8762          3

[200000 rows x 2 columns]

## tqdm

In [1]:
from tqdm import tqdm
import time
for i in tqdm(range(10)):
    time.sleep(1)

100%|██████████| 10/10 [00:10<00:00,  1.00s/it]


## 找出与测试样例具有相同特征值,且该特征值仅出现过一次的训练样例

In [40]:
a = pd.DataFrame([[0,1,2],[2,3,4],[4,5,6]],columns=['a','b','c'])
b = pd.Series([0,3,5]).rename({0:'a',1:'b',2:'c'})

In [41]:
t = a==b
t

a      b      c
0   True  False  False
1  False   True  False
2  False  False  False

In [50]:
features = np.sum(t,axis=0)==1
#features = features[features==True]
features

a     True
b     True
c    False
dtype: bool

In [59]:
# 选出那些仅出现一次的样例idx
idx_mask = np.any(t.loc[:,features],axis=1)
idx_mask
a.iloc[np.argwhere(idx_mask)[:,0]]

0     True
1     True
2    False
dtype: bool

a  b  c
0  0  1  2
1  2  3  4

## np.hstack

横向扩充

In [62]:
np.hstack([a,a])

array([[0, 1, 2, 0, 1, 2],
       [2, 3, 4, 2, 3, 4],
       [4, 5, 6, 4, 5, 6]])

## Logging包

In [ ]:
import logging

def get_logger():
    FORMAT = '[%(levelname)s]%(asctime)s:%(name)s:%(message)s'
    logging.basicConfig(format=FORMAT)
    logger = logging.getLogger('main')
    logger.setLevel(logging.DEBUG)
    return logger

logger = get_logger()